### The given dataset doesn't include categery information of products. Therefore, I got Amazon product dataset[1, 2], and it will be used as the training set in my model.
### With the following script, first, the data will be loaded. Second, in data cleaning, only product information and category are selected, because they are needed in training the following model. The model only aims to find so-called 'macro' categories of the products, so this information is selected.

#### [1] Ups and downs: Modeling the visual evolution of fashion trends with one-class collaborative filtering,  R. He, J. McAuley, WWW, 2016

#### [2] Image-based recommendations on styles and substitutes, J. McAuley, C. Targett, J. Shi, A. van den Hengel, SIGIR, 2015

# load dataset

#### The dataset includes descriptions, price, sales-rank, brand info, and co-purchasing link about 9.4 million products.

In [3]:
import pandas as pd
import numpy as np
import gzip

def parse(path):
  g = gzip.open(path, 'rb')
  for l in g:
    yield eval(l)

def getDF(path):
  i = 0
  df = {}
  for d in parse(path):
    df[i] = d
    i += 1
  return pd.DataFrame.from_dict(df, orient='index')

df = getDF('input/metadata.json.gz')

In [12]:
df.head(10)

,asin,salesRank,imUrl,categories,title,description,price,related,brand
0,0001048791,{'Books': 6334800},http://ecx.images-amazon.com/images/I/51MKP0T4...,[[Books]],"The Crucible: Performed by Stuart Pankin, Jero...",NaN,NaN,NaN,NaN
1,0000143561,{'Movies & TV': 376041},http://g-ecx.images-amazon.com/images/G/01/x-s...,"[[Movies & TV, Movies]]","Everyday Italian (with Giada de Laurentiis), V...","3Pack DVD set - Italian Classics, Parties and ...",12.99,"{'also_viewed': ['B0036FO6SI', 'B000KL8ODE', '...",NaN
2,0000037214,{'Clothing': 1233557},http://ecx.images-amazon.com/images/I/31mCncNu...,"[[Clothing, Shoes & Jewelry, Girls], [Clothing...",Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,NaN,6.99,"{'also_viewed': ['B00JO8II76', 'B00DGN4R1Q', '...",Big Dreams
3,0000032069,NaN,http://ecx.images-amazon.com/images/I/51EzU6qu...,"[[Sports & Outdoors, Other Sports, Dance, Clot...",Adult Ballet Tutu Cheetah Pink,NaN,7.89,"{'also_bought': ['0000032050', 'B00D0DJAEG', '...",BubuBibi
4,0000031909,{'Toys & Games': 201847},http://ecx.images-amazon.com/images/I/41xBoP0F...,"[[Sports & Outdoors, Other Sports, Dance]]",Girls Ballet Tutu Neon Pink,High quality 3 layer ballet tutu. 12 inches in...,7.00,"{'also_bought': ['B002BZX8Z6', 'B00JHONN1S', '...",Unknown
5,0000032034,NaN,http://ecx.images-amazon.com/images/I/21GNUNIa...,"[[Sports & Outdoors, Other Sports, Dance, Clot...",Adult Ballet Tutu Yellow,NaN,7.87,"{'also_bought': ['B00D2JSRFQ', '0000032042', '...",BubuBibi
6,0000589012,{'Movies & TV': 1084845},http://ecx.images-amazon.com/images/I/519%2B1k...,"[[Movies & TV, Movies]]",Why Don't They Just Quit? DVD Roundtable Discu...,NaN,15.95,"{'also_bought': ['B000Z3N1HQ', '0578045427', '...",NaN
7,0001048775,{'Books': 13243226},http://ecx.images-amazon.com/images/I/5166EBHD...,[[Books]],Measure for Measure: Complete &amp; Unabridged,William Shakespeare is widely regarded as the ...,NaN,NaN,NaN
8,0000031852,{'Toys & Games': 211836},http://ecx.images-amazon.com/images/I/51fAmVkT...,"[[Sports & Outdoors, Other Sports, Dance]]",Girls Ballet Tutu Zebra Hot Pink,TUtu,3.17,"{'also_bought': ['B00JHONN1S', 'B002BZX8Z6', '...",Coxlures
9,0001048236,{'Books': 8973864},http://ecx.images-amazon.com/images/I/51DH145C...,[[Books]],The Sherlock Holmes Audio Collection,"&#34;One thing is certain, Sherlockians, put a...",9.26,"{'also_viewed': ['1442300191', '9626349786', '...",NaN

# Clean data

### Keep title and categories

In [17]:
# the dataset is huge. Select useful data from it.
del df['asin']
del df['salesRank']
del df['imUrl']
del df['description']
del df['price']
del df['related']
del df['brand']
df.head(3)

,categories,title
0,[[Books]],"The Crucible: Performed by Stuart Pankin, Jero..."
1,"[[Movies & TV, Movies]]","Everyday Italian (with Giada de Laurentiis), V..."
2,"[[Clothing, Shoes & Jewelry, Girls], [Clothing...",Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...

In [18]:
# export data for future use
export_csv = df.to_csv (r'selectedAmazonProductData.csv', index = None, header=True)

In [121]:
# select macro categories
df["primary_category_list"] = df['categories'].str[0]

In [128]:
df.head(10)

,categories,title,primary_category_list,subcategory1
1,"[[Movies & TV, Movies]]","Everyday Italian (with Giada de Laurentiis), V...","[Movies & TV, Movies]",Movies & TV
2,"[[Clothing, Shoes & Jewelry, Girls], [Clothing...",Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,"[Clothing, Shoes & Jewelry, Girls]","Clothing, Shoes & Jewelry"
3,"[[Sports & Outdoors, Other Sports, Dance, Clot...",Adult Ballet Tutu Cheetah Pink,"[Sports & Outdoors, Other Sports, Dance, Cloth...",Sports & Outdoors
4,"[[Sports & Outdoors, Other Sports, Dance]]",Girls Ballet Tutu Neon Pink,"[Sports & Outdoors, Other Sports, Dance]",Sports & Outdoors
5,"[[Sports & Outdoors, Other Sports, Dance, Clot...",Adult Ballet Tutu Yellow,"[Sports & Outdoors, Other Sports, Dance, Cloth...",Sports & Outdoors
6,"[[Movies & TV, Movies]]",Why Don't They Just Quit? DVD Roundtable Discu...,"[Movies & TV, Movies]",Movies & TV
8,"[[Sports & Outdoors, Other Sports, Dance]]",Girls Ballet Tutu Zebra Hot Pink,"[Sports & Outdoors, Other Sports, Dance]",Sports & Outdoors
18,"[[Sports & Outdoors, Other Sports, Dance, Clot...",Adult Ballet Tutu Purple,"[Sports & Outdoors, Other Sports, Dance, Cloth...",Sports & Outdoors
28,"[[Movies & TV, Movies]]",Understanding Seizures and Epilepsy DVD,"[Movies & TV, Movies]",Movies & TV
34,"[[Movies & TV, Movies]]",Live in Houston [VHS],"[Movies & TV, Movies]",Movies & TV

In [124]:
df["subcategory1"] = df['primary_category_list'].str[0]

In [144]:
category = df.groupby('subcategory1').size()
category = category.rename('Number')
category = category.sort_values(ascending=False)

In [145]:
category[category > 2000] / category.sum() * 100

subcategory1
Clothing, Shoes & Jewelry    21.146984
Sports & Outdoors             7.805495
Electronics                   7.297273
CDs & Vinyl                   7.241780
Home & Kitchen                6.435396
Cell Phones & Accessories     5.106373
Toys & Games                  4.940952
Automotive                    4.875576
Digital Music                 3.981946
Tools & Home Improvement      3.953919
Health & Personal Care        3.863314
Beauty                        3.816966
Movies & TV                   2.870037
Grocery & Gourmet Food        2.529490
Office Products               1.977674
Arts, Crafts & Sewing         1.729071
Pet Supplies                  1.627921
Patio, Lawn & Garden          1.603135
Baby                          1.050332
Musical Instruments           1.008299
Apps for Android              0.906502
Video Games                   0.719652
Industrial & Scientific       0.695086
Amazon Instant Video          0.451373
Amazon Fashion                0.355599
Software                      0.260945
Appliances                    0.171636
Baby Products                 0.147571
All Electronics               0.111503
Christian                     0.109986
All Beauty                    0.096908
Kindle Store                  0.091429
Collectibles & Fine Art       0.090015
International                 0.073314
Dance & Electronic            0.068145
Computers                     0.065538
Miscellaneous                 0.060604
Home Improvement              0.058086
Alternative Rock              0.056863
Kitchen & Dining              0.055243
Pop                           0.051915
Office & School Supplies      0.048837
Rock                          0.037070
Classical                     0.033918
Jazz                          0.033255
Folk                          0.029573
Name: Number, dtype: float64

In [146]:
category[category <= 3000] / category.sum() * 100

subcategory1
Rock                                        0.037070
Classical                                   0.033918
Jazz                                        0.033255
Folk                                        0.029573
Luxury Beauty                               0.028365
Buy a Kindle                                0.027909
R&B                                         0.025066
MP3 Players & Accessories                   0.024625
Magazine Subscriptions                      0.021753
Country                                     0.021164
Wine                                        0.018218
Hard Rock & Metal                           0.013461
Blues                                       0.013255
New Age                                     0.009853
Rap & Hip-Hop                               0.008689
Gift Cards                                  0.007099
Camera & Photo                              0.006804
Car Electronics                             0.006009
GPS & Navigation                            0.005317
Classic Rock                                0.004639
Children's Music                            0.004580
Broadway & Vocalists                        0.004197
Appstore for Android                        0.002239
Furniture & D&#233;cor                      0.001591
Davis                                       0.000869
Purchase Circles                            0.000486
Sports Collectibles                         0.000398
All Credit Cards                            0.000309
Latin Music                                 0.000162
Entertainment                               0.000088
Gift Cards Store                            0.000074
Microsoft                                   0.000059
Amazon Coins                                0.000059
Amazon Fire TV                              0.000044
Celebrate your Birthday with Nickelodeon    0.000029
Gospel                                      0.000029
Publishers                                  0.000029
Collectible Coins                           0.000015
#508510                                     0.000015
Name: Number, dtype: float64

## drop 'books' category, because there seems no book in target data

In [127]:
df = df[df.subcategory1 != 'Books']
df = df[df.subcategory1 != '']

In [142]:
df = df[df.subcategory1 != '']

## we could tell that in this dataset, there exist a lot of music categories that seems not to exist in our target dataset. Also, the above data tells that these categories only take a small percent of purchase. Therefore, for simplicity, these small categories are ignored in my model.

In [147]:
categoryList = category[category > 3000].index.tolist()
categoryList

['Clothing, Shoes & Jewelry',
 'Sports & Outdoors',
 'Electronics',
 'CDs & Vinyl',
 'Home & Kitchen',
 'Cell Phones & Accessories',
 'Toys & Games',
 'Automotive',
 'Digital Music',
 'Tools & Home Improvement',
 'Health & Personal Care',
 'Beauty',
 'Movies & TV',
 'Grocery & Gourmet Food',
 'Office Products',
 'Arts, Crafts & Sewing',
 'Pet Supplies',
 'Patio, Lawn & Garden',
 'Baby',
 'Musical Instruments',
 'Apps for Android',
 'Video Games',
 'Industrial & Scientific',
 'Amazon Instant Video',
 'Amazon Fashion',
 'Software',
 'Appliances',
 'Baby Products',
 'All Electronics',
 'Christian',
 'All Beauty',
 'Kindle Store',
 'Collectibles & Fine Art',
 'International',
 'Dance & Electronic',
 'Computers',
 'Miscellaneous',
 'Home Improvement',
 'Alternative Rock',
 'Kitchen & Dining',
 'Pop',
 'Office & School Supplies']

In [151]:
categoryList.remove('Pop')
categoryList.remove('Dance & Electronic')
categoryList.remove('Digital Music')

In [152]:
categoryList

['Clothing, Shoes & Jewelry',
 'Sports & Outdoors',
 'Electronics',
 'CDs & Vinyl',
 'Home & Kitchen',
 'Cell Phones & Accessories',
 'Toys & Games',
 'Automotive',
 'Tools & Home Improvement',
 'Health & Personal Care',
 'Beauty',
 'Movies & TV',
 'Grocery & Gourmet Food',
 'Office Products',
 'Arts, Crafts & Sewing',
 'Pet Supplies',
 'Patio, Lawn & Garden',
 'Baby',
 'Musical Instruments',
 'Apps for Android',
 'Video Games',
 'Industrial & Scientific',
 'Amazon Instant Video',
 'Amazon Fashion',
 'Software',
 'Appliances',
 'Baby Products',
 'All Electronics',
 'Christian',
 'All Beauty',
 'Kindle Store',
 'Collectibles & Fine Art',
 'International',
 'Computers',
 'Miscellaneous',
 'Home Improvement',
 'Alternative Rock',
 'Kitchen & Dining',
 'Office & School Supplies']

In [153]:
df = df[df['subcategory1'].isin(categoryList)]

In [154]:
# export data for future use
export_csv = df.to_csv (r'selectedAmazonProductData1.csv', index = None, header=True)

## seperate 'Clothing, Shoes & Jewelry' into three subcategories

In [158]:
df[df['subcategory1'] == 'Clothing, Shoes & Jewelry']

,categories,title,primary_category_list,subcategory1,subcategory2,subcategory3,subcategory4
2,"[[Clothing, Shoes & Jewelry, Girls], [Clothing...",Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,"[Clothing, Shoes & Jewelry, Girls]","Clothing, Shoes & Jewelry",Girls,NaN,NaN
44,"[[Clothing, Shoes & Jewelry, Girls, Clothing, ...",Ballet Dress-Up Fairy Tutu,"[Clothing, Shoes & Jewelry, Girls, Clothing, A...","Clothing, Shoes & Jewelry",Girls,Clothing,Active
56971,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Jewelry Accessories,Jewelry Boxes & Organizers
303166,"[[Clothing, Shoes & Jewelry, Women, Accessorie...",RiZ Women's Beautify Crafted &frac12; Rimmed F...,"[Clothing, Shoes & Jewelry, Women, Accessories...","Clothing, Shoes & Jewelry",Women,Accessories,Sunglasses & Eyewear Accessories
303167,"[[Clothing, Shoes & Jewelry, Women, Accessorie...",Lantin White Visor Wrap Around Ski Style Aviat...,"[Clothing, Shoes & Jewelry, Women, Accessories...","Clothing, Shoes & Jewelry",Women,Accessories,Sunglasses & Eyewear Accessories
303182,"[[Clothing, Shoes & Jewelry, Women, Accessorie...",NVC Unisex Light Weight Silver 'Dakota' Glasse...,"[Clothing, Shoes & Jewelry, Women, Accessories...","Clothing, Shoes & Jewelry",Women,Accessories,Sunglasses & Eyewear Accessories
303194,"[[Clothing, Shoes & Jewelry, Women, Accessorie...",Kismeth Eyewear Classic Large Top Gun Aviator ...,"[Clothing, Shoes & Jewelry, Women, Accessories...","Clothing, Shoes & Jewelry",Women,Accessories,Sunglasses & Eyewear Accessories
303200,"[[Clothing, Shoes & Jewelry, Women, Accessorie...",Max-MPH Black - Large Wayfarer Sunglasses Avai...,"[Clothing, Shoes & Jewelry, Women, Accessories...","Clothing, Shoes & Jewelry",Women,Accessories,Sunglasses & Eyewear Accessories
303318,"[[Clothing, Shoes & Jewelry, Women, Accessorie...",FX1 Small Adult Aviator Sunglasses with Silver...,"[Clothing, Shoes & Jewelry, Women, Accessories...","Clothing, Shoes & Jewelry",Women,Accessories,Sunglasses & Eyewear Accessories
303422,"[[Clothing, Shoes & Jewelry, Women, Accessorie...",Riz Small Unisex (Mens/ Womens) Black Classic ...,"[Clothing, Shoes & Jewelry, Women, Accessories...","Clothing, Shoes & Jewelry",Women,Accessories,Sunglasses & Eyewear Accessories
438308,"[[Clothing, Shoes & Jewelry, Women, Accessorie...",Red Crocodile Embossed Leather Travel Wallet,"[Clothing, Shoes & Jewelry, Women, Accessories...","Clothing, Shoes & Jewelry",Women,Accessories,"Wallets, Card Cases & Money Organizers"
438331,"[[Clothing, Shoes & Jewelry, Luggage & Travel ...",Vera Bradley Tote Blue Rhapsody,"[Clothing, Shoes & Jewelry, Luggage & Travel G...","Clothing, Shoes & Jewelry",Luggage & Travel Gear,Luggage,Travel Totes
463177,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Twilight Saga: New Moon Alice Chocker Necklace...,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Movie & TV Fan,Accessories
463375,"[[Clothing, Shoes & Jewelry, Women, Petite, Fa...",Bear Ear Hoodie Jacket &amp; Poms on drawstrin...,"[Clothing, Shoes & Jewelry, Women, Petite, Fas...","Clothing, Shoes & Jewelry",Women,Petite,Fashion Hoodies & Sweatshirts
525336,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Rectangle Blank Puzzle (12-pack),"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,NaN
546467,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Spanish Third-year Pin Set of 10,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Novelty,Clothing
546498,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Viva Espanol Pins Set of 10,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Novelty,Clothing
589119,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Eagle / Hawk / Parrot Nose Bird Beak Costume Mask,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Masks
755878,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Death Note Anime Manga: Cross Logo necklace,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,NaN
1032923,"[[Clothing, Shoes & Jewelry, Women, Watches, W...",New Lava Iron Blue Samurai Metal LED Faceless ...,"[Clothing, Shoes & Jewelry, Women, Watches, Wr...","Clothing, Shoes & Jewelry",Women,Watches,Wrist Watches
1032965,"[[Clothing, Shoes & Jewelry, Men, Watches, Wri...",Men Automatic U1 Skeleton Mechanical Watch Met...,"[Clothing, Shoes & Jewelry, Men, Watches, Wris...","Clothing, Shoes & Jewelry",Men,Watches,Wrist Watches
1052247,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Pink Bikini Swimwear Glow in the Dark Fashion,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Costumes
1052344,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Bikini Swimwear Blue Glow in the Dark Fashion,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Costumes
1052417,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Glow in the Dark Fashion Beaded Penuar,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Costumes
1052536,"[[Clothing, Shoes & Jewelry, Women, Watches, W...",Watch Black Match Iphone,"[Clothing, Shoes & Jewelry, Women, Watches, Wr...","Clothing, Shoes & Jewelry",Women,Watches,Wrist Watches
1052782,"[[Clothing, Shoes & Jewelry, Men, Watches, Poc...",New Smart Steampunk Globle Motorcycle Carving ...,"[Clothing, Shoes & Jewelry, Men, Watches, Pock...","Clothing, Shoes & Jewelry",Men,Watches,Pocket Watches
1052796,"[[Clothing, Shoes & Jewelry, Men, Watches, Wri...",Stylish Triple Time Zones Black Leather Milita...,"[Clothing, Shoes & Jewelry, Men, Watches, Wris...","Clothing, Shoes & Jewelry",Men,Watches,Wrist Watches
1052798,"[[Clothing, Shoes & Jewelry, Women, Watches, W...",Luxury Dark Angel's Heart Women Crystal Bracel...,"[Clothing, Shoes & Jewelry, Women, Watches, Wr...","Clothing, Shoes & Jewelry",Women,Watches,Wrist Watches
1052804,"[[Clothing, Shoes & Jewelry, Men, Watches, Poc...",NEW Embossed Sailing Vessel Voyage Retro Bronz...,"[Clothing, Shoes & Jewelry, Men, Watches, Pock...","Clothing, Shoes & Jewelry",Men,Watches,Pocket Watches
1069263,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Tibet Silver Inlay Red Jade Men's Ring,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Novelty,Jewelry
...,...,...,...,...,...,...,...
9428775,"[[Clothing, Shoes & Jewelry, Women, Clothing, ...",New Women's Scrawl Print Romper 2 Pieces Tank ...,"[Clothing, Shoes & Jewelry, Women, Clothing, J...","Clothing, Shoes & Jewelry",Women,Clothing,"Jumpsuits, Rompers & Overalls"
9428812,"[[Clothing, Shoes & Jewelry, Women, Clothing, ...",Mossy Oak Babydoll Camo Lingerie (Top &amp; Pa...,"[Clothing, Shoes & Jewelry, Women, Clothing, L...","Clothing, Shoes & Jewelry",Women,Clothing,"Lingerie, Sleep & Lounge"
9428851,"[[Clothing, Shoes & Jewelry, Women], [Clothing...",Ana Silver Co Labradorite 925 Sterling Silver ...,"[Clothing, Shoes & Jewelry, Women]","Clothing, Shoes & Jewelry",Women,NaN,NaN
9428863,"[[Clothing, Shoes & Jewelry, Women, Clothing, ...",ROSEMANDY Women's Sexy Halter Backless Elastic...,"[Clothing, Shoes & Jewelry, Women, Clothing, L...","Clothing, Shoes & Jewelry",Women,Clothing,"Lingerie, Sleep & Lounge"
9428875,"[[Clothing, Shoes & Jewelry, Women, Clothing, ...",American Apparel Dark Wash High-Waist Jean Cuf...,"[Clothing, Shoes & Jewelry, Women, Clothing, S...","Clothing, Shoes & Jewelry",Women,Clothing,Shorts
9428925,"[[Clothing, Shoes & Jewelry, Men, Clothing, Ac...",Under Armour Men's UA Canelo H&amp;H T-Shirt,"[Clothing, Shoes & Jewelry, Men, Clothing, Act...","Clothing, Shoes & Jewelry",Men,Clothing,Active
9429085,"[[Clothing, Shoes & Jewelry, Boot Shop, Women,...",Bamboo Dita-04 Chestnut Women Casual Boots,"[Clothing, Shoes & Jewelry, Boot Shop, Women, ...","Clothing, Shoes & Jewelry",Boot Shop,Women,Fashion
9429094,"[[Clothing, Shoes & Jewelry, Women], [Clothing...",Ana Silver Co Rose Quartz 925 Sterling Silver ...,"[Clothing, Shoes & Jewelry, Women]","Clothing, Shoes & Jewelry",Women,NaN,NaN
9429128,"[[Clothing, Shoes & Jewelry, Men], [Clothing, ...",BeWild Brand&reg; - LeBron James Forgiven Welc...,"[Clothing, Shoes & Jewelry, Men]","Clothing, Shoes & Jewelry",Men,NaN,NaN
9429135,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Thomas Jefferson Costume Kit Colonial Wig &amp...,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Wigs
9429163,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Thomas Jefferson Costume Kit Colonial Wig &amp...,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Wigs
9429232,"[[Clothing, Shoes & Jewelry, Women], [Clothing...",Cubic Zirconia Sterling Silver 925 Infinity To...,"[Clothing, Shoes & Jewelry, Women]","Clothing, Shoes & Jewelry",Women,NaN,NaN
9429272,"[[Clothing, Shoes & Jewelry, Men, Accessories,...",Kenneth Cole Reaction Mens Big &amp; Tall Leat...,"[Clothing, Shoes & Jewelry, Men, Accessories, ...","Clothing, Shoes & Jewelry",Men,Accessories,Belts
9429358,"[[Clothing, Shoes & Jewelry, Women, Shoes, Pum...",Bonnibel Karla-1 Silver Glitter Women Pumps,"[Clothing, Shoes & Jewelry, Women, Shoes, Pumps]","Clothing, Shoes & Jewelry",Women,Shoes,Pumps
9429368,"[[Clothing, Shoes & Jewelry, Boys, Clothing, F...",POCKET FRENZ&reg; BOYS 4-12 DRAGON T-REX DINOS...,"[Clothing, Shoes & Jewelry, Boys, Clothing, Fa...","Clothing, Shoes & Jewelry",Boys,Clothing,Fashion Hoodies & Sweatshirts
9429389,"[[Clothing, Shoes & Jewelry, Men, Clothing, Ja...",Chouyatou Men's Pu Leather Mid-length Washed T...,"[Clothing, Shoes & Jewelry, Men, Clothing, Jac...","Clothing, Shoes & Jewelry",Men,Clothing,Jackets & Coats
9429415,"[[Clothing, Shoes & Jewelry, M, Minnetonka]]",Minnetonka Velcro Back Flap Bootie (Infant),"[Clothing, Shoes & Jewelry, M, Minnetonka]","Clothing, Shoes & Jewelry",M,Minnetonka,NaN
9429582,"[[Clothing, Shoes & Jewelry, Baby, Baby Girls,...",Baby Girls 3rd Birthday Toddler Tutu Tank Top ...,"[Clothing, Shoes & Jewelry, Baby, Baby Girls, ...","Clothing, Shoes & Jewelry",Baby,Baby Girls,Clothing
9429611,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Fred Flintstone Costume Adult Caveman Costume ...,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Costumes
9429627,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Betty Rubble Costume Adult Flintstone Costume ...,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Costumes
9429629,"[[Clothing, Shoes & Jewelry, Women, Clothing, ...",Musical Holiday Women's Sateen Bridal Wedding ...,"[Clothing, Shoes & Jewelry, Women, Clothing, D...","Clothing, Shoes & Jewelry",Women,Clothing,Dresses
9429636,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Betty Rubble Costume Adult Flintstone Costume ...,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Costumes
9429669,"[[Clothing, Shoes & Jewelry, Novelty, Costumes...",Wilma Flintstone Costume Adult Flintstones Cos...,"[Clothing, Shoes & Jewelry, Novelty, Costumes ...","Clothing, Shoes & Jewelry","Novelty, Costumes & More",Costumes & Accessories,Costumes
9429689,"[[Clothing, Shoes & Jewelry, Girls, Clothing, ...",Bbmour-kids Girls Boys Frozen Anna and Elsa Pr...,"[Clothing, Shoes & Jewelry, Girls, Clothing, J...","Clothing, Shoes & Jewelry",Girls,Clothing,Jackets & Coats
9429767,"[[Clothing, Shoes & Jewelry, Jewelry: Internat...",Invicta Men's Pro Diver 8928C 2,"[Clothing, Shoes & Jewelry, Jewelry: Internati...","Clothing, Shoes & Jewelry",Jewelry: International Shipping Available,NaN,NaN
9429795,"[[Clothing, Shoes & Jewelry, Women], [Clothing...",It's Sterling Silver Heart Necklace with Made ...,"[Clothing, Shoes & Jewelry, Women]","Clothing, Shoes & Jewelry",Women,NaN,NaN
9429849,"[[Clothing, Shoes & Jewelry, Women, Clothing, ...",Realtree Ruffle Spa Wrap + Mossy Oak Pink Scru...,"[Clothing, Shoes & Jewelry, Women, Clothing, S...","Clothing, Shoes & Jewelry",Women,Clothing,Swimsuits & Cover Ups
9429881,"[[Clothing, Shoes & Jewelry, Women], [Clothing...",Women's Empire Waist with Tummy Control/ Full ...,"[Clothing, Shoes & Jewelry, Women]","Clothing, Shoes & Jewelry",Women,NaN,NaN
9429913,"[[Clothing, Shoes & Jewelry, Women, Clothing, ...",Skirts 'N Scarves Women's Long Cotton Maxi Pai...,"[Clothing, Shoes & Jewelry, Women, Clothing, S...","Clothing, Shoes & Jewelry",Women,Clothing,Skirts
9430079,"[[Clothing, Shoes & Jewelry, Baby, Baby Girls,...",American Posh Baby Short Sleeve Onesie,"[Clothing, Shoes & Jewelry, Baby, Baby Girls, ...","Clothing, Shoes & Jewelry",Baby,Baby Girls,Clothing

In [157]:
df["subcategory2"] = df['primary_category_list'].str[1]
df["subcategory3"] = df['primary_category_list'].str[2]
df["subcategory4"] = df['primary_category_list'].str[3]

In [162]:
category = df[df['subcategory1'] == 'Clothing, Shoes & Jewelry'].groupby('subcategory3').size()
category = category.rename('Number')
category = category.sort_values(ascending=False)
category

subcategory3
Clothing                   315977
Accessories                 73456
Shoes                       57020
Novelty                     46935
Jewelry                     45816
Costumes & Accessories      32982
Baby Girls                  22481
Handbags & Wallets          17973
Watches                     15355
Band & Music Fan            10372
Baby Boys                   10295
Luggage                      7567
Backpacks                    7548
Nike                         7307
Jewelry Accessories          6684
Work Wear & Uniforms         6533
Calvin Klein                 6352
Petite                       4780
Women                        4677
Nautica                      4314
New Jewelry                  4011
Dickies                      3327
Merrell                      3040
Travel Accessories           3001
Carhartt                     2960
Lucky Brand                  2952
COACH                        2790
Shoe Care & Accessories      2755
Exotic Apparel               2732
Messenger Bags               2524
                            ...
Carlos Falchi                   1
Pink Studio                     1
Polliwalks                      1
Cienta                          1
Rainbow Steps                   1
Report Signature                1
Rocky Boot Company              1
Rex for Robert Wayne            1
David Spencer                   1
Delman                          1
Beverly Feldman                 1
Sophia Visconti                 1
Lava                            1
Leatherbay                      1
Toss Designs                    1
trace                           1
Little Laundry                  1
The Flexx                       1
Lovely People                   1
Lulu Guinness                   1
Mad Rock                        1
Magnanni                        1
Draven                          1
Manitobah Mukluks               1
Missoni                         1
StorkSak                        1
Moda Spana                      1
Moni Moni                       1
Springboost                     1
Pelle Moda                      1
Name: Number, Length: 764, dtype: int64

In [163]:
clothingShoesJewelry = ['Clothing','Accessories', 'Shoes', 'Jewelry', 'Watches', 'Costumes & Accessories']

In [164]:
# define macro categories
df['macro categories'] = np.where(df['subcategory1'] == 'Clothing, Shoes & Jewelry', df["subcategory3"], df["subcategory1"])

In [178]:
df.head()

,categories,title,primary_category_list,subcategory1,subcategory2,subcategory3,subcategory4,macro categories
1,"[[Movies & TV, Movies]]","Everyday Italian (with Giada de Laurentiis), V...","[Movies & TV, Movies]",Movies & TV,Movies,NaN,NaN,Movies & TV
3,"[[Sports & Outdoors, Other Sports, Dance, Clot...",Adult Ballet Tutu Cheetah Pink,"[Sports & Outdoors, Other Sports, Dance, Cloth...",Sports & Outdoors,Other Sports,Dance,Clothing,Sports & Outdoors
4,"[[Sports & Outdoors, Other Sports, Dance]]",Girls Ballet Tutu Neon Pink,"[Sports & Outdoors, Other Sports, Dance]",Sports & Outdoors,Other Sports,Dance,NaN,Sports & Outdoors
5,"[[Sports & Outdoors, Other Sports, Dance, Clot...",Adult Ballet Tutu Yellow,"[Sports & Outdoors, Other Sports, Dance, Cloth...",Sports & Outdoors,Other Sports,Dance,Clothing,Sports & Outdoors
6,"[[Movies & TV, Movies]]",Why Don't They Just Quit? DVD Roundtable Discu...,"[Movies & TV, Movies]",Movies & TV,Movies,NaN,NaN,Movies & TV

In [174]:
df = df[(df['subcategory1'] != 'Clothing, Shoes & Jewelry') | (df['subcategory3'].isin(clothingShoesJewelry))]

In [177]:
df = df[df['macro categories'] != '']

In [180]:
category = df.groupby('macro categories').size()
category = category.rename('Number')
category = category.sort_values(ascending=False)
category

macro categories
Sports & Outdoors            529989
Electronics                  495481
CDs & Vinyl                  491713
Home & Kitchen               436960
Cell Phones & Accessories    346720
Toys & Games                 335488
Automotive                   331049
Clothing                     315977
Tools & Home Improvement     268469
Health & Personal Care       262317
Beauty                       259170
Movies & TV                  194874
Grocery & Gourmet Food       171751
Office Products              134283
Arts, Crafts & Sewing        117403
Pet Supplies                 110535
Patio, Lawn & Garden         108852
Accessories                   73456
Baby                          71317
Musical Instruments           68463
Apps for Android              61551
Shoes                         57020
Video Games                   48864
Industrial & Scientific       47196
Jewelry                       45816
Costumes & Accessories        32982
Amazon Instant Video          30648
Amazon Fashion                24145
Software                      17718
Watches                       15355
Appliances                    11654
Baby Products                 10020
All Electronics                7571
Christian                      7468
All Beauty                     6580
Kindle Store                   6208
Collectibles & Fine Art        6112
International                  4978
Computers                      4450
Miscellaneous                  4115
Home Improvement               3944
Alternative Rock               3861
Kitchen & Dining               3751
Office & School Supplies       3316
Name: Number, dtype: int64

In [183]:
df.head()

                                               title   macro categories
1  Everyday Italian (with Giada de Laurentiis), V...        Movies & TV
3                     Adult Ballet Tutu Cheetah Pink  Sports & Outdoors
4                        Girls Ballet Tutu Neon Pink  Sports & Outdoors
5                           Adult Ballet Tutu Yellow  Sports & Outdoors
6  Why Don't They Just Quit? DVD Roundtable Discu...        Movies & TV

In [182]:
del df['primary_category_list']
del df['categories']
del df['subcategory1']
del df['subcategory2']
del df['subcategory3']
del df['subcategory4']

In [184]:
# export data for future use
export_csv = df.to_csv (r'output/selectedAmazonProductData_final.csv', index = None, header=True)